# Generated by Django 2.2 on 2019-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_description',
            field=models.TextField(max_length=100),
        ),
    ]
