# Generated by Django 2.2 on 2019-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20190524_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
