# Generated by Django 2.2 on 2019-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20190524_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
    ]
