# Generated by Django 2.2 on 2019-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0011_product_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_product',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
